import os
# print(os.listdir("."))
# print(os.system('cmd'))
# print(os.remove('del.txt'))
# print(os.unlink('read1.txt'))
# print(os.rename('read1.txt','read2.txt'))
# print(os.pardir)
# print(os.chdir("d:\\"))
# print(os.getcwd())
#print(os.mkdir('./test'))
#print(os.rmdir('./test'))
#print(os.makedirs('./test/test1'))
# print(os.removedirs('./test/test1'))
# print(os.stat('test.txt'))
# print(os.environ)
# print(os.sep)
# print(os.name)
# print(os.linesep)
print(os.pathsep)