import sys
# print(sys.argv)
# print(sys.path)

# print(sys.modules.keys)
# print(sys.modules)

# print(sys.exc_info())
# print(sys.exec_prefix)
# print(sys.version)
# print(sys.platform)
# print(sys.copyright)
# print(sys.api_version)
# print(sys.getdefaultencoding())
# print(sys.getfilesystemencoding())
# print(sys.getwindowsversion())
# print(sys.builtin_module_names)
# print(sys.executable)
# sys.stdin.read()
sys.stdout.write('a')
